#!/bin/sh

# JavaScript + NodeJS

check_nodejs() {
  if [ -e package.json ]; then
    # We found a package.json file, let's see if it contains a test command.
    if grep -q '^[[:space:]]*"test"' package.json; then
      return 0
    else
      return 0
    fi
  else
    return 1
  fi
}

run_nodejs() {
  echo "npm test"
  npm test
}

# Rust + Cargo

check_cargo() {
  [ -e Cargo.toml ]
}

run_cargo() {
  echo "cargo test"
  cargo test
}

check_and_run() {
  if check_nodejs; then
    run_nodejs
    exit
  elif check_cargo; then
    run_cargo
    exit
  fi
}

# The root of the project.
TOP=""

# Check if git exists on the system.
if [ -x "$(command -v git)" ]; then
  # Find the root of the git repository if we are inside one.
  TOP=$(git rev-parse --show-toplevel 2> /dev/null)
  if [ $? -ne 0 ]; then
    echo "Not in git repo"
    TOP=$HOME
  fi
fi

nothing_found() {
  echo "No tests found :'("
  exit 1
}

main() {
  while :
  do
    check_and_run
    if [ $PWD = $TOP ]; then
      nothing_found
    fi
    cd ..
    if [ $PWD = $HOME -o  ]; then
      nothing_found
    fi
  done
}

main
